// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatinaryProject.Data;

namespace StatinaryProject.Migrations
{
    [DbContext(typeof(StatinaryProjectContext))]
    partial class StatinaryProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StatinaryProject.Model.Product_Information", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shop_Id")
                        .HasColumnType("int");

                    b.HasKey("Product_Id");

                    b.HasIndex("Shop_Id");

                    b.ToTable("Product_Information");
                });

            modelBuilder.Entity("StatinaryProject.Model.Shop_Information", b =>
                {
                    b.Property<int>("Shop_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_Id");

                    b.ToTable("Shop_Information");
                });

            modelBuilder.Entity("StatinaryProject.Model.Product_Information", b =>
                {
                    b.HasOne("StatinaryProject.Model.Shop_Information", "Shop_Information")
                        .WithMany("Product_Information")
                        .HasForeignKey("Shop_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop_Information");
                });

            modelBuilder.Entity("StatinaryProject.Model.Shop_Information", b =>
                {
                    b.Navigation("Product_Information");
                });
#pragma warning restore 612, 618
        }
    }
}
